webtalk_init -webtalk_dir /home/jason/matlab/Projects/ZynqBF_2tx/simulation/ZynqBF_2tx_sim.sim/sim_1/behav/xsim/xsim.dir/ZynqBF_2tx_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb  8 13:18:01 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211510650_1777533435_210679306_925" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a0a4ed2b-7ac7-46bd-bfdd-7b0be689c0ed" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d6dad242fa8448e985b337bf1f38d691" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3880.615 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.21_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "164228_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3215374686 -regid "211510650_1777533435_210679306_925" -xml /home/jason/matlab/Projects/ZynqBF_2tx/simulation/ZynqBF_2tx_sim.sim/sim_1/behav/xsim/xsim.dir/ZynqBF_2tx_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/jason/matlab/Projects/ZynqBF_2tx/simulation/ZynqBF_2tx_sim.sim/sim_1/behav/xsim/xsim.dir/ZynqBF_2tx_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/jason/matlab/Projects/ZynqBF_2tx/simulation/ZynqBF_2tx_sim.sim/sim_1/behav/xsim/xsim.dir/ZynqBF_2tx_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
