-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\ZynqBF_2tx_fpga\ZynqBF_2t_ip_src_peakdetect_ch1.vhd
-- Created: 2019-02-08 23:33:51
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ZynqBF_2t_ip_src_peakdetect_ch1
-- Source Path: ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.ZynqBF_2t_ip_src_ZynqBF_2tx_fpga_pkg.ALL;

ENTITY ZynqBF_2t_ip_src_peakdetect IS
  GENERIC(
        CHANNEL                           :   integer := 1
        );
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        rst                               :   IN    std_logic;
        din                               :   IN    vector_of_std_logic_vector16(0 TO 1);  -- sfix16_En15 [2]
        vin                               :   IN    std_logic;
        en                                :   IN    std_logic;
        addr                              :   IN    std_logic_vector(14 DOWNTO 0);  -- ufix15
        index                             :   OUT   std_logic_vector(14 DOWNTO 0);  -- ufix15
        step                              :   OUT   std_logic;
        peak_found                        :   OUT   std_logic;
        probe                             :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
        );
END ZynqBF_2t_ip_src_peakdetect;


ARCHITECTURE rtl OF ZynqBF_2t_ip_src_peakdetect IS

  -- Component Declarations
  COMPONENT ZynqBF_2t_ip_src_correlator_wrapper
    GENERIC(
          CHANNEL                         : integer := 1
          );
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          rx                              :   IN    vector_of_std_logic_vector16(0 TO 1);  -- sfix16_En15 [2]
          valid                           :   IN    std_logic;
          en                              :   IN    std_logic;
          rst                             :   IN    std_logic;
          dout                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          dval                            :   OUT   std_logic;
          step                            :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT ZynqBF_2t_ip_src_peak_fsm
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          t_cross                         :   IN    std_logic;
          cnt_end                         :   IN    std_logic;
          scan_peak                       :   OUT   std_logic;
          peak_found                      :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT ZynqBF_2t_ip_src_running_max
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          din                             :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          en                              :   IN    std_logic;
          rst                             :   IN    std_logic;
          new_max                         :   OUT   std_logic;
          max_val                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
          );
  END COMPONENT;

  COMPONENT ZynqBF_2t_ip_src_store_index
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          din                             :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          update                          :   IN    std_logic;
          dout                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : ZynqBF_2t_ip_src_correlator_wrapper
    USE ENTITY work.ZynqBF_2t_ip_src_correlator_wrapper(rtl);

  FOR ALL : ZynqBF_2t_ip_src_peak_fsm
    USE ENTITY work.ZynqBF_2t_ip_src_peak_fsm(rtl);

  FOR ALL : ZynqBF_2t_ip_src_running_max
    USE ENTITY work.ZynqBF_2t_ip_src_running_max(rtl);

  FOR ALL : ZynqBF_2t_ip_src_store_index
    USE ENTITY work.ZynqBF_2t_ip_src_store_index(rtl);

  -- Signals
  SIGNAL addr_unsigned                    : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL Delay9_reg                       : vector_of_unsigned15(0 TO 1);  -- ufix15 [2]
  SIGNAL Delay9_out1                      : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL Add1_sub_temp                    : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL Add1_out1                        : signed(15 DOWNTO 0);  -- int16
  SIGNAL index_in                         : signed(15 DOWNTO 0);  -- int16
  SIGNAL corr_vout                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL correlator1_out2                 : std_logic;
  SIGNAL correlator1_out3                 : std_logic;
  SIGNAL corr_vout_signed                 : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Delay4_out1                      : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Compare_To_Constant_out1         : std_logic;
  SIGNAL peak_fsm_out1                    : std_logic;
  SIGNAL Logical_Operator5_out1           : std_logic;
  SIGNAL count_20_steps_out1              : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant1_out1        : std_logic;
  SIGNAL Logical_Operator7_out1           : std_logic;
  SIGNAL peak_fsm_out2                    : std_logic;
  SIGNAL update_index                     : std_logic;
  SIGNAL running_max_out2                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL stored_index                     : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL stored_index_signed              : signed(15 DOWNTO 0);  -- int16
  SIGNAL Data_Type_Conversion_out1        : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL Delay10_out1                     : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL Logical_Operator3_out1           : std_logic;
  SIGNAL Logical_Operator2_out1           : std_logic;
  SIGNAL Delay3_out1                      : std_logic;
  SIGNAL Delay6_out1                      : std_logic;

BEGIN
  u_correlator_wrapper : ZynqBF_2t_ip_src_correlator_wrapper
    GENERIC MAP (
              CHANNEL => CHANNEL
              )
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              rx => din,  -- sfix16_En15 [2]
              valid => vin,
              en => en,
              rst => rst,
              dout => corr_vout,  -- sfix32_En16
              dval => correlator1_out2,
              step => correlator1_out3
              );

  u_peak_fsm : ZynqBF_2t_ip_src_peak_fsm
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              t_cross => Compare_To_Constant_out1,
              cnt_end => Logical_Operator7_out1,
              scan_peak => peak_fsm_out1,
              peak_found => peak_fsm_out2
              );

  u_running_max : ZynqBF_2t_ip_src_running_max
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              din => std_logic_vector(Delay4_out1),  -- sfix32_En16
              en => peak_fsm_out1,
              rst => peak_fsm_out2,
              new_max => update_index,
              max_val => running_max_out2  -- sfix32_En16
              );

  u_store_index : ZynqBF_2t_ip_src_store_index
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              din => std_logic_vector(index_in),  -- int16
              update => update_index,
              dout => stored_index  -- int16
              );

  addr_unsigned <= unsigned(addr);

  Delay9_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay9_reg <= (OTHERS => to_unsigned(16#0000#, 15));
      ELSIF enb = '1' THEN
        Delay9_reg(0) <= addr_unsigned;
        Delay9_reg(1) <= Delay9_reg(0);
      END IF;
    END IF;
  END PROCESS Delay9_process;

  Delay9_out1 <= Delay9_reg(1);

  Add1_sub_temp <= signed(resize(Delay9_out1, 17)) - to_signed(16#01000#, 17);
  Add1_out1 <= Add1_sub_temp(15 DOWNTO 0);

  Delay11_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        index_in <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        index_in <= Add1_out1;
      END IF;
    END IF;
  END PROCESS Delay11_process;


  corr_vout_signed <= signed(corr_vout);

  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_out1 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        Delay4_out1 <= corr_vout_signed;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  
  Compare_To_Constant_out1 <= '1' WHEN corr_vout_signed >= to_signed(6553600, 32) ELSE
      '0';

  Logical_Operator5_out1 <= correlator1_out3 AND peak_fsm_out1;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 20
  count_20_steps_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        count_20_steps_out1 <= to_unsigned(16#00#, 8);
      ELSIF enb = '1' THEN
        IF Logical_Operator5_out1 = '1' THEN 
          IF count_20_steps_out1 >= to_unsigned(16#14#, 8) THEN 
            count_20_steps_out1 <= to_unsigned(16#00#, 8);
          ELSE 
            count_20_steps_out1 <= count_20_steps_out1 + to_unsigned(16#01#, 8);
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS count_20_steps_process;


  
  Compare_To_Constant1_out1 <= '1' WHEN count_20_steps_out1 = to_unsigned(16#14#, 8) ELSE
      '0';

  Logical_Operator7_out1 <= correlator1_out3 AND Compare_To_Constant1_out1;

  stored_index_signed <= signed(stored_index);

  Data_Type_Conversion_out1 <= unsigned(stored_index_signed(14 DOWNTO 0));

  Delay10_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay10_out1 <= to_unsigned(16#0000#, 15);
      ELSIF enb = '1' THEN
        Delay10_out1 <= Data_Type_Conversion_out1;
      END IF;
    END IF;
  END PROCESS Delay10_process;


  index <= std_logic_vector(Delay10_out1);

  Logical_Operator3_out1 <=  NOT Compare_To_Constant1_out1;

  Logical_Operator2_out1 <= correlator1_out3 AND Logical_Operator3_out1;

  Delay3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay3_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay3_out1 <= Logical_Operator2_out1;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  Delay6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay6_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay6_out1 <= Logical_Operator7_out1;
      END IF;
    END IF;
  END PROCESS Delay6_process;



  step <= Delay3_out1;

  peak_found <= Delay6_out1;

  probe <= corr_vout;

END rtl;

