# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jason/matlab/Projects/ZynqBF_2tx/hdl_prj/ipcore/ZynqBF_2t_ip_v1_0/prj_ip/prj_ip.srcs/sources_1/ip/gsram4_1/gsram4.xci
# IP: The module: 'gsram4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jason/matlab/Projects/ZynqBF_2tx/hdl_prj/ipcore/ZynqBF_2t_ip_v1_0/prj_ip/prj_ip.srcs/sources_1/ip/gsram4_1/gsram4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gsram4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/jason/matlab/Projects/ZynqBF_2tx/hdl_prj/ipcore/ZynqBF_2t_ip_v1_0/prj_ip/prj_ip.srcs/sources_1/ip/gsram4_1/gsram4.xci
# IP: The module: 'gsram4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jason/matlab/Projects/ZynqBF_2tx/hdl_prj/ipcore/ZynqBF_2t_ip_v1_0/prj_ip/prj_ip.srcs/sources_1/ip/gsram4_1/gsram4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gsram4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
