#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Apr 09 10:36:39 EDT 2019
# SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim ZynqBF_2tx_tb_behav -key {Behavioral:sim_2:Functional:ZynqBF_2tx_tb} -tclbatch ZynqBF_2tx_tb.tcl -view /home/jason/matlab/Projects/ZynqBF_2tx/hdl_prj/vivado_ip_prj/ZynqBF_2tx_tb_behav.wcfg -log simulate.log
