-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\ZynqBF_2tx_fpga\ZynqBF_2t_ip_src_rx_ram_i.vhd
-- Created: 2019-02-08 23:33:51
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ZynqBF_2t_ip_src_rx_ram_i
-- Source Path: ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/rx_ram_i
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ZynqBF_2t_ip_src_rx_ram_i IS
  PORT( clk                               :   IN    std_logic;
        ram_rst                           :   IN    std_logic;
	    enb                               :   IN    std_logic;
        i                                 :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
        wdata                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        waddr                             :   IN    std_logic_vector(8 DOWNTO 0);  -- ufix9
        -- we                                :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
        we                                :   IN    std_logic; --_vector(63 DOWNTO 0);  -- ufix64
        raddr                             :   IN    std_logic_vector(9 DOWNTO 0);  -- ufix10
        shift                             :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
        dout                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        probe                             :   OUT   std_logic_vector(8 DOWNTO 0)  -- ufix9
        );
END ZynqBF_2t_ip_src_rx_ram_i;


ARCHITECTURE rtl OF ZynqBF_2t_ip_src_rx_ram_i IS

  -- Component Declarations
  COMPONENT ZynqBF_2t_ip_src_get_bit
    PORT( u                               :   IN    std_logic_vector(63 DOWNTO 0);  -- ufix64
          ind                             :   IN    std_logic_vector(8 DOWNTO 0);  -- ufix9
          y                               :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT ZynqBF_2t_ip_src_SimpleDualPortRAM_generic
    GENERIC( AddrWidth                    : integer;
             DataWidth                    : integer
             );
    PORT( clk                             :   IN    std_logic;
          ram_rst                         :   IN    std_logic;
	      enb                             :   IN    std_logic;
          wr_din                          :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
          wr_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          wr_en                           :   IN    std_logic;
          rd_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          rd_dout                         :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : ZynqBF_2t_ip_src_get_bit
    USE ENTITY work.ZynqBF_2t_ip_src_get_bit(rtl);

  FOR ALL : ZynqBF_2t_ip_src_SimpleDualPortRAM_generic
    USE ENTITY work.ZynqBF_2t_ip_src_SimpleDualPortRAM_generic(rtl);

  -- Signals
  SIGNAL i_unsigned                       : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Sum1_out1                        : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL y                                : std_logic;
  SIGNAL shift_unsigned                   : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Relational_Operator_relop1       : std_logic;
  SIGNAL raddr_unsigned                   : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL raddr_dtc                        : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Sum_out1                         : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Switch_out1                      : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Simple_Dual_Port_RAM_out1        : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  -- u_get_bit : ZynqBF_2t_ip_src_get_bit
    -- PORT MAP( u => we,  -- ufix64
              -- ind => std_logic_vector(Sum1_out1),  -- ufix9
              -- y => y
              -- );

  u_Simple_Dual_Port_RAM : ZynqBF_2t_ip_src_SimpleDualPortRAM_generic
    GENERIC MAP( AddrWidth => 9,
                 DataWidth => 16
                 )
    PORT MAP( clk => clk,
	          ram_rst => ram_rst,
              enb => enb,
              wr_din => wdata,
              wr_addr => waddr,
              wr_en => we,
              rd_addr => std_logic_vector(Switch_out1),
              rd_dout => Simple_Dual_Port_RAM_out1
              );

  i_unsigned <= unsigned(i);

  Sum1_out1 <= resize(resize(i_unsigned, 7) + to_unsigned(16#01#, 7), 9);

  shift_unsigned <= unsigned(shift);

  
  Relational_Operator_relop1 <= '1' WHEN i_unsigned < shift_unsigned ELSE
      '0';

  raddr_unsigned <= unsigned(raddr);

  raddr_dtc <= raddr_unsigned(8 DOWNTO 0);

  Sum_out1 <= resize(to_unsigned(16#001#, 11) + resize(raddr_unsigned, 11), 9);

  
  Switch_out1 <= raddr_dtc WHEN Relational_Operator_relop1 = '0' ELSE
      Sum_out1;

  probe <= std_logic_vector(Switch_out1);

  dout <= Simple_Dual_Port_RAM_out1;

END rtl;

