# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jason/matlab/Projects/ZynqBF_2tx/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/ip/gsram3/gsram3.xci
# IP: The module: 'gsram3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jason/matlab/Projects/ZynqBF_2tx/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/ip/gsram3/gsram3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gsram3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/jason/matlab/Projects/ZynqBF_2tx/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/ip/gsram3/gsram3.xci
# IP: The module: 'gsram3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jason/matlab/Projects/ZynqBF_2tx/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/ip/gsram3/gsram3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gsram3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
