-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\ZynqBF_2tx_fpga\ZynqBF_2t_ip_src_gs_selector.vhd
-- Created: 2019-02-08 23:33:51
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ZynqBF_2t_ip_src_gs_selector
-- Source Path: ZynqBF_2tx_fpga/channel_estimator/gs_selector
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ZynqBF_2t_ip_src_gs_selector IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        pd1                               :   IN    std_logic;
        pd2                               :   IN    std_logic;
        en                                :   IN    std_logic;
        gs_sel                            :   OUT   std_logic_vector(0 TO 1)  -- boolean [2]
        );
END ZynqBF_2t_ip_src_gs_selector;


ARCHITECTURE rtl OF ZynqBF_2t_ip_src_gs_selector IS

  -- Signals
  SIGNAL Delay4_out1                      : std_logic;
  SIGNAL Delay1_out1                      : std_logic;
  SIGNAL Delay2_out1                      : std_logic;
  SIGNAL Vector_Concatenate_out1          : std_logic_vector(0 TO 1);  -- boolean [2]
  SIGNAL Switch1_out1                     : std_logic_vector(0 TO 1);  -- boolean [2]
  SIGNAL Switch1_out1_1                   : std_logic_vector(0 TO 1);  -- boolean [2]

BEGIN
  Delay4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay4_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay4_out1 <= en;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  Delay1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay1_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay1_out1 <= pd1;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  Delay2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay2_out1 <= '0';
      ELSIF enb = '1' THEN
        Delay2_out1 <= pd2;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  Vector_Concatenate_out1(0) <= Delay1_out1;
  Vector_Concatenate_out1(1) <= Delay2_out1;

  
  Switch1_out1_1 <= Switch1_out1 WHEN Delay4_out1 = '0' ELSE
      Vector_Concatenate_out1;

  reduced_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Switch1_out1 <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        Switch1_out1 <= Switch1_out1_1;
      END IF;
    END IF;
  END PROCESS reduced_process;


  gs_sel <= Switch1_out1;

END rtl;

