-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\ZynqBF_2tx_fpga\ZynqBF_2t_ip_src_all_u.vhd
-- Created: 2019-02-08 23:33:51
-- 
-- Generated by MATLAB 9.5 and HDL Coder 3.13
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ZynqBF_2t_ip_src_all_u
-- Source Path: ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/all_u
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ZynqBF_2t_ip_src_all_u IS
  PORT( u                                 :   IN    std_logic_vector(0 TO 7);  -- boolean [8]
        y                                 :   OUT   std_logic
        );
END ZynqBF_2t_ip_src_all_u;


ARCHITECTURE rtl OF ZynqBF_2t_ip_src_all_u IS

BEGIN
  all_u_output : PROCESS (u)
    VARIABLE y_temp : std_logic;
  BEGIN
    --MATLAB Function 'channel_estimator/peakdetect_ch1/correlator1/all_u'
    y_temp := '1';

    FOR k IN 0 TO 7 LOOP
      y_temp := y_temp AND u(k);
    END LOOP;

    y <= y_temp;
  END PROCESS all_u_output;


END rtl;

