// -------------------------------------------------------------
// 
// File Name: hdl_prj/hdlsrc/util_mw_bypass_user_logic/util_mw_bypass_user_logic_addr_decoder.v
// Created: 2018-08-08 16:25:38
// 
// Generated by MATLAB 9.5 and HDL Coder 3.13
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: util_mw_bypass_user_logic_addr_decoder
// Source Path: util_mw_bypass_user_logic/util_mw_bypass_user_logic_axi_lite/util_mw_bypass_user_logic_addr_decoder
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module util_mw_bypass_user_logic_addr_decoder
          (clk,
           reset,
           data_write,
           addr_sel,
           wr_enb,
           rd_enb,
           read_ip_timestamp,
           data_read,
           write_axi_enable,
           write_sel);


  input   clk;
  input   reset;
  input   [31:0] data_write;  // ufix32
  input   [13:0] addr_sel;  // ufix14
  input   wr_enb;  // ufix1
  input   rd_enb;  // ufix1
  input   [31:0] read_ip_timestamp;  // ufix32
  output  [31:0] data_read;  // ufix32
  output  write_axi_enable;  // ufix1
  output  write_sel;  // ufix1


  wire enb;
  wire decode_sel_ip_timestamp;  // ufix1
  wire const_1;  // ufix1
  wire [31:0] const_0;  // ufix32
  reg [31:0] read_reg_ip_timestamp;  // ufix32
  wire [31:0] decode_rd_ip_timestamp;  // ufix32
  wire decode_sel_axi_enable;  // ufix1
  wire reg_enb_axi_enable;  // ufix1
  wire data_in_axi_enable;  // ufix1
  reg  write_reg_axi_enable;  // ufix1
  wire decode_sel_sel;  // ufix1
  wire reg_enb_sel;  // ufix1
  wire data_in_sel;  // ufix1
  reg  write_reg_sel;  // ufix1


  assign decode_sel_ip_timestamp = addr_sel == 14'b00000000000010;



  assign const_1 = 1'b1;



  assign enb = const_1;

  assign const_0 = 32'b00000000000000000000000000000000;



  always @(posedge clk or posedge reset)
    begin : reg_ip_timestamp_process
      if (reset == 1'b1) begin
        read_reg_ip_timestamp <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          read_reg_ip_timestamp <= read_ip_timestamp;
        end
      end
    end



  assign decode_rd_ip_timestamp = (decode_sel_ip_timestamp == 1'b0 ? const_0 :
              read_reg_ip_timestamp);



  assign data_read = decode_rd_ip_timestamp;

  assign decode_sel_axi_enable = addr_sel == 14'b00000000000001;



  assign reg_enb_axi_enable = decode_sel_axi_enable & wr_enb;



  assign data_in_axi_enable = data_write[0];



  always @(posedge clk or posedge reset)
    begin : reg_axi_enable_process
      if (reset == 1'b1) begin
        write_reg_axi_enable <= 1'b1;
      end
      else begin
        if (enb && reg_enb_axi_enable) begin
          write_reg_axi_enable <= data_in_axi_enable;
        end
      end
    end



  assign write_axi_enable = write_reg_axi_enable;

  assign decode_sel_sel = addr_sel == 14'b00000001000000;



  assign reg_enb_sel = decode_sel_sel & wr_enb;



  assign data_in_sel = data_write[0];



  always @(posedge clk or posedge reset)
    begin : reg_sel_process
      if (reset == 1'b1) begin
        write_reg_sel <= 1'b0;
      end
      else begin
        if (enb && reg_enb_sel) begin
          write_reg_sel <= data_in_sel;
        end
      end
    end



  assign write_sel = write_reg_sel;

endmodule  // util_mw_bypass_user_logic_addr_decoder

