open_system('gm_ZynqBF_2tx_fpga');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ZynqBF_2tx_fpga/channel_estimator', 'user2');
annotate_port('gm_ZynqBF_2tx_fpga/channel_estimator', 0, 1, 'cp : 14.901 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1', 'user2');
annotate_port('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1', 0, 1, 'cp : 14.901 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1', 'user2');
annotate_port('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1', 0, 1, 'cp : 14.901 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/sum_elements_i_instance1', 'user2');
annotate_port('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/sum_elements_i_instance1', 0, 1, 'cp : 3.2745 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/t13', 'user2');
annotate_port('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/t13', 0, 1, 'cp : 3.2745 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/Delay1', 'user1');
annotate_port('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/Delay1', 1, 1, 'cp : 14.901 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/Sum of Elements1', 'user2');
annotate_port('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/Sum of Elements1', 0, 1, 'cp : 14.737 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/sum_elements_i_instance1/Switch1', 'user2');
annotate_port('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/sum_elements_i_instance1/Switch1', 0, 1, 'cp : 1.637 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/sum_elements_i_instance1/Compare To Constant2', 'user2');
annotate_port('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/sum_elements_i_instance1/Compare To Constant2', 0, 1, 'cp : 1.22 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/sum_elements_i_instance1/HDL Counter1', 'user1');
annotate_port('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/sum_elements_i_instance1/HDL Counter1', 0, 1, 'cp : 0.474 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/sum_elements_i_instance1/Add', 'user2');
annotate_port('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/sum_elements_i_instance1/Add', 0, 1, 'cp : 3.2745 ns');
