open_system('ZynqBF_2tx_fpga');
open_system('gm_ZynqBF_2tx_fpga');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/correlator_i/Delay1', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/correlator_i/Switch', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/correlator_i_instance1/Multiply-Add', 'user1');
hilite_system('ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/correlator_i/Multiply-Add', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/correlator_i_instance1/Delay1', 'user1');
hilite_system('ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/correlator_i/Delay1', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/correlator_i_instance1/Switch', 'user1');
hilite_system('ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/correlator_i/Switch', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ZynqBF_2tx_fpga/channel_estimator/peakdetect_ch1/correlator1/correlator_i/Multiply-Add', 'user1');
